version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: