spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email

jwt:
  secret: ${JWT_SECRET}

app:
  frontend-url: ${FRONTEND_URL}

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}