spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            exclude: static/**,public/**,templates/**
        livereload:
            enabled: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        scope:
                            - openid
                            - profile
                            - email

jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

app:
    frontend-url: ${FRONTEND_URL:http://localhost:5173}
